### ISSUE TITLE
Some text DOES NOT back up in the app

### ISSUE THREAD

**Issue by pete1182** [jberkel/sms-backup-plus#1016]
i know there's been a few issues with this app but i still think its one of the best back-up app available for android. my app still works as long as i manually perform it. however i just recently discovered there are a few sms texts from certain phone #s that did not back up in my gmail at all. like i said i dont mind doing it manually, but is there any other way for me to store those text to back up somehow. please help!!!

**Comment by pete1182** [comment]
by the way this is for my samsung galaxy s20 ultra

**Comment by kurahaupo** [comment]
> however i just recently discovered there are a few SMS texts from certain
> phone #s that did not back up in my gmail at all.

Check whether the messages from those senders are "Advanced Messaging".
(Typically it's turned on per-device, so that a particular person will send
all of their "SMS" and "MMS" messages as "AM" messages instead.

Unfortunately they're visually indistinguishable, you need to explicitly
check the metadata to find out which format they're in.

Last I checked, Google had yet to document their new API for accessing these
AM messages; until then there's not much that can be done, other that ask
your correspondents not to use AM when sending to you.

-Martin

**Comment by kurahaupo** [comment]
Does disabling AM/RCS at the sender fix this?

**Comment by kurahaupo** [comment]
no response, closing
