### ISSUE TITLE
Beginning July 8, 2020, SMS Backup+ will no longer have access to your Gmail data

### ISSUE THREAD

**Issue by jmorgannz** [jberkel/sms-backup-plus#1026]
I removed the issue template as this relates to a google policy issue and it's effect on SMS Backup+, not a sequence of events leading to a reproducible bug.

Today I received this email:

> 
>**From: Google Apps Developers <noreply-apps-developer@google.com>
>Subject: Protecting the data in your Google Account
>Date: 1 Jul 2020, 02:57**
>Hello,
>Beginning July 8, 2020, the following app will no longer have access to your Gmail data:
>
>    SMS Backup+
>
>Google has always worked to design our tools and services with security at their core. 
>Last year, we proactively updated the Google User Data Policy to better protect Gmail users.
>All apps listed above have not passed our required verification process and, as a result, will no longer be able to access your Gmail data starting July 8, 2020.
>
>Without access to your Gmail data, this app may not work as intended.
>If you have any questions, please contact the developer of the app.
>You can also use the Security Checkup tool to view, manage, and remove any apps that you have given access to your Google Account.
>
>Thanks,
>The Google Accounts team

**Comment by bferrell** [comment]
I got the same message.  I've found this to be enormously useful.  Please don't allow it to die

**Comment by al-right** [comment]
I got a similar message too.

> All apps listed above have not passed our required verification process and, as a result, will no longer be able to access your Gmail data starting July 8, 2020.

Too bad Google did not write what the problems were as to qualify and pass the verification process or where to find the specific details about the problems they identified.

**Comment by kurahaupo** [comment]
@al-right actually Google have said: the short version of the reason that SMS Backup+ has not been granted access to the Gmail "sensitive scope" is that *it is not an app whose primary purpose is to be a user-focused email client*.

That's a somewhat intractable problem to overcome.
The fact that it never *sends* email actually counts *against* it.

**Comment by kurahaupo** [comment]
@jmorgannz @bferrell  @al-right  I'm guessing you're on G-suite accounts, so you've had an extra year. Welcome to the rest of the world. :-(

We have a fair work-around, though it involves the user enabling 3rd-party IMAP access to their Gmail account, which is not ideal.

Further details on issue #959.

**Comment by jmorgannz** [comment]
@kurahaupo I'm not on G-suite. Regular consumer gmail here.

**Comment by al-right** [comment]
@kurahaupo I'm not on G-suite either. Also regular consumer gmail here. I did #973 back when Google kicked my instance of SMS Backup+ from accessing my account in August 2019 and it has worked ever since without having to re-authenticate. I will try to re-authenticate when they finally kick me this time and see if the Firefox trick still works. But I guess eventually I have to surrender to another method unless SMS Backup+ could get a simple send email/check email functionality... Beggars belief - I know ;)

**Comment by al-right** [comment]
I can confirm today that trying to connect using https://github.com/jberkel/sms-backup-plus/issues/973#issuecomment-521420655 using XOAuth2 does no longer work. Firefox tells that login with google is temporarily deactivated for this app (SMS Backup +). The exact wording in English I do not have (because it is written in Danish, my first language.)
Too bad, but that is how things are. :)
