### ISSUE TITLE
How to fix XOAuth authorization error on Android

### ISSUE THREAD

**Issue by flordagirl** [jberkel/sms-backup-plus#1028]
How do I fix this?

"XOAuth authorization error. Please make sure you enabled IMAP in your Gmail account settings."

### Please specify the following:

* Android version: 9
* Phone model / brand: LG K40
* SMS Backup+ version installed: 1.5.11

**Comment by kurahaupo** [comment]
@flordagirl

Can you confirm that IMAP is already enabled on your Gmail account? (Use the "settings" cogwheel icon.)

**Comment by flordagirl** [comment]
> @flordagirl
> 
> Can you confirm that IMAP is already enabled on your Gmail account? (Use the "settings" cogwheel icon.)
> 
> As per #970.

Yes, it's been enabled.  Now what?
![image](https://user-images.githubusercontent.com/53923749/87975413-9a8d9b00-ca99-11ea-82e4-727f6cad3a20.png)

**Comment by flordagirl** [comment]
Why did you close it? IMAP has always been enabled. The same error is still there and the app is unusable.

________________________________

**Comment by kurahaupo** [comment]
When exactly do you see "XOAuth authorization error"? I ask because if SMS Backup+ is correctly configured, it won't even _try_ to use XOAUTH to access Gmail.

Please go through your gmail settings and create an app password for IMAP (if you have not already done so), and then go through the app settings and check that it is configured to use IMAP with that app password, as explained in issue #970 .

If you initially configured SMS Backup+  a long time ago, you may need to ensure that XOAUTH is _not_ being used, by going into **Settings** → **Advanced settings** → **Legacy settings** and _disable_ **Connect**.

**Note:** SMS Backup+ does still use XOAUTH to access calendars, if you've configured it to save your call log as calendar records, and if that's when the error appears, that's an entirely different debugging problem.

**Comment by cauerego** [comment]
renaming and repurposing the app would be a great idea. indeed, being able to search messages is more important and relevant than "just" [being a (good and real) backup](https://cregox.net/backup)...

but here's to an even better one, for me:

get away from google! there are very good technical reasons why: https://cregox.net/delete

by all means, keep it working with it if you can... but focus on more open things like disroot or delta chat.

**Comment by kurahaupo** [comment]
@flordagirl note that the browser work-around no longer works; you will need to use the IMAP method instead.

(My apologies, I assumed, based on the error message, that you had already configured SMS Backup+ to use IMAP.)

**Comment by kurahaupo** [comment]
@flordagirl if you upgrade to version 1.16β then the new configuration screen makes it much clearer that the old XOAUTH method is deprecated, and unlikely to work until such time as Google can be convinced to approve this app for sensitive scope access.

**Comment by flordagirl** [comment]
> @flordagirl if you upgrade to version 1.6β then the new configuration screen makes it much clearer that the old XOAUTH method is deprecated, and unlikely to work until such time as Google can be convinced to approve this app for sensitive scope access.

I've already tried that. My reply is late because I was unable to reply until now. If you are currently still using SMS Backup+ on an android device along with the feature where it automatically backs up your texts to gmail, could you please send me the steps on how you got it to work? Like I've mentioned previously I've already spent hours looking through all the posts here and trying the steps mentioned by others. None of the work arounds are working for my anymore.

**Comment by kurahaupo** [comment]
Yes I'm still using it, and the last time I set it up was January 2020 when I bought this phone.

I have 2-factor authentication enabled on my Gmail account, with the authenticator app and SMS as options. I've enabled IMAP access into Gmail.

I generated an app password, then told SMS Backup+ to use it. (You should do that separately for each device where you install it, otherwise Google may object to you using the same login from multiple sources, and invalidate the app password.

That's all. No other magic required.

-Martin

**Comment by flordagirl** [comment]
> I have 2-factor authentication enabled on my Gmail account, 
**I already have that on. It's been on since 2019;**

with the authenticator app and SMS as options.

 I've enabled IMAP access into Gmail.
> **So have I.**
> I generated an app password, then told SMS Backup+ to use it. (You should do that separately for each device where you install it, otherwise Google may object to you using the same login from multiple sources, and invalidate the app password.
> **Already did that too.**


NEXT!!!
