### ISSUE TITLE
Some SMS messages successfully backed up to Gmail, not restoring to new phone

### ISSUE THREAD

**Issue by Jeffx11** [jberkel/sms-backup-plus#1039]
**Expected behavior:**  Use sms-backup-plus to move all sms messages from old phone to new phone by backing them up to Gmail, then with RESTORE ALL selected, restoring them to the new phone.

**Actual behavior:**  Some of the messages that were backed up successfully to Gmail are missing from the new phone after RESTORING ALL.

**Steps to reproduce the behavior:**  Re-attempted to backup and restore, including switching the default messages app on the new phone from Samsung Messages to Google Messages, but this did not fix the problem.

Android version: 9
Make/model: Samsung Galaxy S8 (SM-G950U)
SMS Backup+ version installed: 1.5.11 
Messaging app:  Google Messages (tried with Samsung Messages, previously)

**Comment by kurahaupo** [comment]
@Jeffx11 by any chance were you using Google Hangouts on your old phone to read & send SMS?

I ask because it that was the case, then SMS Backup+ would not have been involved in backing them up - Hangouts automatically incorporates messages into your email view. As a result, they would not have had the email (MIME) headers set correctly for SMS Backup+ to be able to restore them correctly.

Another possibility is that you have a large number of messages, and are encountering limits imposed by IMAP. (Typically only a few thousand can be processed in a single IMAP session.)

**Comment by kurahaupo** [comment]
@Jeffx11 are you still experiencing this problem?

**Comment by Jeffx11** [comment]
We switched to a different SMS backup app, so no I am not, but others may be still experiencing the problem.  Google Hangouts was not being used. It was probably the large number of messages IMAP limit as you suggested.  There were definitely more than a few thousand.  

Thanks for responding.
