### ISSUE TITLE
Call log entries stored into wrong Google Calendar

### ISSUE THREAD

**Issue by fuxoft** [jberkel/sms-backup-plus#1044]
All my Call log entries don't appear in "Call log" calendar but in calendar "Pupen rozvrh", which is (coincidentally?) the most recent Google calendar I've created. Curiously, in the "Call log settings" page, the option "Calendar used for call logs" is set to "None" and is greyed out (cannot be clicked / changed).

### Expected behaviour

Call log entries should appear in my "Call log" Google Calendar.

### Actual behaviour

All call log entries appear in my "Pupen rozvrh" Google Calendar.

### Steps to reproduce the behaviour

Configure SMS Backup+, do initial backup.

### Please specify the following:

* Android version
Android 10
* Phone model / brand
Nokia 7.2
* SMS Backup+ version installed
SMS Backup+ 1.6.0-BETA2
* Messaging app
Google Messages

**Comment by kurahaupo** [comment]
When I [investigated that issue](./963#issuecomment-711801677), the it was one of those "this code is so simple how can it possibly go wrong" kind of errors, so the only reasonable conclusion is that it's an error in a library somewhere.

@fuxoft I'm closing this as a duplicate, but feel free to add comments to #963. If it turns out to be a separate issue then this can be reopened.
