### ISSUE TITLE
Will SMS messages on Gmail disappear once phone with messages is disconnected

### ISSUE THREAD

**Issue by kimreuwer** [jberkel/sms-backup-plus#1085]
Hi! Thank you so much for continuing to update such a helpful app. We used the server name imap.Gmail.com and the sms+ backup worked like a breeze. 

My sister is disconnecting her phone tomorrow. Will the SMS messages automatically disappear after the phone is wiped? We are unsure whether the hosted messages need a continued phone connection.  

thank you 

Version 1.5.11 
Old Phone - Google Pixel 3 

EDIT : the messages stayed on the Gmail server/her Gmail! After light digging I found that IMAP stores a local copy so the messages were successfully saved. Again, thank you!

**Comment by Salmalsalm** [comment]
http://

**Comment by Salmalsalm** [comment]
> http://

**Comment by kurahaupo** [comment]
No. The messages are safe.

One of the key use-cases for this app is to restore messages after a phone has been wiped; it wouldn't be very good at that job if it automatically dropped all the messages when the phone is disconnected.

Firstly, Gmail has no way to track the continued existence of a particular IMAP client device, since it's only identified by the login credentials that you provide. "Disconnect" in this context has nothing to do with actual _connections_, but rather is used as a vague shorthand for "remove the credentials from the client device so that it can't log in"; the server simply has no way to know this has occurred.

You can ask Gmail to issue new credentials at any time; it has no way of knowing whether you plan to use those in a new or existing app installation, and therefore no way of inferring that the "old" device has "gone away".

Secondly, messages stored in Gmail are stored in exactly the same say as emails that arrived normally, which is to say, they're independent copies that don't "belong" to any device. So even if Gmail _did_ somehow track the device connections

Thirdly, the app doesn't even contain the IMAP "delete" and "expunge" commands. It couldn't delete your messages even if it went bizarrely wrong.

One of the key use-cases for this app is to restore messages after a phone has been wiped; it wouldn't be very good at that job if it automatically dropped all the messages when the phone is disconnected.
