### ISSUE TITLE
Samsung Galaxy S4 - won't back up any items

### ISSUE THREAD

**Issue by vinkyw** [jberkel/sms-backup-plus#358]
Hello,

I used to use this app happily enough on the HTC Legend, One S and One X, but I cannot seem to get it to work on the GS4. Instead of backing anything up, it saysit has backed up 0/however many items (see attached picture). It will not back up SMS messages or WhatsApp conversations to Gmail as it won't get past the screen shown. SMS Backup, the one that just creates text files (?) on the phone, does work, however.

I've un/reinstalled a couple of times, and am running version 1.5.5; I've tried it with and without auto backup; I've tried it on wifi and on mobile data; none of these things have made a difference.

Any suggestions would be very much appreciated as I love the app and cannot fathom how to solve this issue!

![sms backup issue](https://f.cloud.github.com/assets/5162079/907791/5c13a0f4-fd64-11e2-87fd-fea1f5152de0.png)

**Comment by Rwaahby** [comment]
In my experience,I used Coolmuster Samsung Backup to backup samsung phone data to computer .And manage data on computer so quickly .Supports Samsung galaxy s3/s4/s5/s6/s7 ...
http://www.samsung-messages-backup.com/resources/how-to-manage-samsung-galaxy-s3-on-pc-mac.html

**Comment by Myutouuhh** [comment]
It's necessary to [transfer data from android to computer](https://www.coolmuster.com/android/android-file-transfer.html)! For example, you can transfer photos and videos to computer for backup. If you want to transfer photos to computer? Actually, there are a large number of methods and softwares and help you finish the job. For example, I will recommended a software called Coolmuster Android Assistant to you because it really helps a lot.
