### ISSUE TITLE
Deleted messages (on phone) are restored as well

### ISSUE THREAD

**Issue by ntziolis** [jberkel/sms-backup-plus#4]
When running a restore ALL messages with the corresponding label (in my case the default SMS) are restored onto the device. Even when they have been previously deleted on the phone.

The optimal solution in my eyes would be something like this:
When a SMS is deleted on the phone add a deleted label to the backed up SMS in Gmail.
On restore on the messages without the deleted filter would be restored.

A first step could be that a label could be specified that is then used to filter out the messages. This label had to be applied manually in gmail.

In general this issue arises since I pretty much never deleted any messages. Often they contain business relevant information, even though I do not have to access that information every day.

**Comment by nonobio** [comment]
Hello,

It is a very old issue but I have a little question:

If I delete messages SMS on my phone and then I restore all messages with SMS Backup+: all is restored, including the deleted message: ok.

But today I tried to delete messages on my Gmail backup, and then I did a restore: I hoped I would have the "cleaned" version of my messages but the deleted messages are always here.

I think it is because the SMS phone database hasn't been deleted before the restoration? Am I right?

If yes, should I delete it manually (if possible), before the restoration, or do you have any other recommendations?

What I would like is to clean my message by deleting which I don't want anymore. I found doing the cleaning on Gmail (or Thunderbird), easier, but is it possible?

Thanks
