### ISSUE TITLE
WhatsApp stopped backing up on March 1st

### ISSUE THREAD

**Issue by hakansr** [jberkel/sms-backup-plus#434]
There were no problems at all until March 1st but whatever I do, not backing up WhatsApp. Others are working well.

Could it be because of the new whatsapp update?

**Comment by jberkel** [comment]
no longer supported

**Comment by MariendeClercq** [comment]
Alas, but it still is working fine though!

2015-06-12 10:34 GMT+02:00 Jan Berkel <notifications@github.com>:

> no longer supported
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jberkel/sms-backup-plus/issues/434#issuecomment-111413847>
> .
>



-- 
Groeten,

Marien

**Comment by MariendeClercq** [comment]
Alas, the new version indeed stopped backing up whatsapp. Jan: Why did you stop this?

**Comment by basanto384** [comment]
Backing up whatsapp is one of the best feature and unique feature which I loved it and hence this was my favorite app too. Though official this was not working, using the TriCrypt I use to back it up, but now no chance :(. Can you please enable this atleast.....we will use Tri-Crypt and use it as it was earlier.

**Comment by jberkel** [comment]
Sorry I removed this feature because it was too complicated to support for the majority of users who always complained that WhatsApp backup was not working as expected.

Of course there are workarounds, but they are too complicated to set up for a non-technical user, and they might also stop working any day.

You can always manually instally an old version which has whatsapp support: https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA5

From my perspective the best solution would be if somebody who is willing to support this feature would fork the app, remove the SMS/Call log related code and release a stand-alone WhatsApp backup tool.

**Comment by MariendeClercq** [comment]
Thanks for your reply, Good idea to keep using the older version of SMS Backup+
