### ISSUE TITLE
unable to backup Whatsapp

### ISSUE THREAD

**Issue by Wiff1** [jberkel/sms-backup-plus#442]
Prior to upgrading my phone from HTC One S to HTC one the whatsapp backup worked fine and backed up everything to my Gmail account fine. But now SMS Backup+ won't backup Whatsapp. Please can you fix this as it is a feature i really love about your app. Config as below.

Android Version: 4.4.2
Phone: HTC One
SMS Backup+ Version: 1.5.5

**Comment by anupamsingh27101983** [comment]
it does not work anymore. all success without key file.

**Comment by jberkel** [comment]
no longer supported, whatsapp will be completely removed in the next version

**Comment by cyclonmaster** [comment]
I want to merge new message received message with old database message(from database backup file). The only way last time I did is backup new message to gmail.

Uninstall whatsapp, install & restore last old backup. Then restore new message from gmail to whatsapp using smsbackup+.

Now it is completely not working due to new whatsapp & smsbackup+ remove it because of complicated solution to cover changes being done by whatsapp.

The only solution I can think of is backup new whatsapp message using mybackuppro(or any backup app), then uninstall whatsapp, install old whatsapp(previously work) and install last smsbackup+ that support backup to gmail. 

Disconnect internet connection. Back dated phone date time to last working date for that whatsapp version. Restore whatsapp data using mybackuppro. Check whatsapp while still offline. Close & Kill whatsapp process using cleanmaster.

Connect to internet(online), BACKUP whatsapp message to gmail using old smsbackup+. Once finish, check whatsapp msg in gmail. Then uninstall and install same old whatsapp version and restore old whatsapp database while still in back dated setting. Then RESTORE whatsapp from gmail to whatsapp using old smsbackup+.

Now can update date to normal and update whatsapp.

This is the solution I can think still work. I want to test it.

I wonder what whatsapp version that last working with smsbackup+ that support and working backup/retore to gmail?

Which Whatsapp? http://www.apkmirror.com/apk/whatsapp-inc/whatsapp/
I suppose last is smsbackup+ 1.5.9-BETA5 https://github.com/jberkel/sms-backup-plus/releases
