### ISSUE TITLE
received MMS never backing up

### ISSUE THREAD

**Issue by sampenguin** [jberkel/sms-backup-plus#459]
After getting a Samsung Galaxy S5, and getting the 1.5.5 version of this, I noticed that incoming MMS messages are not getting backed up. I looked at the other MMS issues listed here and none of them are the same (i.e. i'm not getting them mislabeled, they just aren't there). Which is unfortunate, because it's not just the media content that's missing, the text that comes included with it is also missing.

I know that in at least one case of this, the sender is using iOS, which I know does weird things with MMS when Android receives them.

**Comment by dabrosch** [comment]
I thought I was having the exact same problem with my Samsung Galaxy Core Prime, but it turns out that I found the MMS messages received from others, they were wrongly being recorded as being sent  from myself! I still get some MMS messages recorded as sent to me from the right sender, but it is inconsistent.

**Comment by kurahaupo** [comment]
Does this problem still exist in the most recent version of SMS Backup? (There have been several updates to SMS Backup since this issue was raised.)

**Comment by kurahaupo** [comment]
No response, closing issue
