### ISSUE TITLE
Gmail doesn't support XOAUTH anymore

### ISSUE THREAD

**Issue by mtomana** [jberkel/sms-backup-plus#554]
"Server does not support XOAUTH".
Google turned off XOAUTH. Only XOAUTH2 is now supported.
Detailt: https://developers.google.com/gmail/xoauth_migration

**Comment by jberkel** [comment]
Thanks for the info. I'll try to get an update out soon.

**Comment by opello** [comment]
I ran in to this yesterday and "disconnecting" (and then removing the authorization) and "reconnecting" to my GMail account seemed to fix things.  I saved a debug log before and after and saw the change from XOAUTH to XOAUTH2.  This was all using version 1.5.8.

**Comment by mtomana** [comment]
Yep, I have to confirm that it works, just like opello said :) But how is it possible? Is this just a workaround?

**Comment by opello** [comment]
It seems like [this is the announcement](https://developers.google.com/gmail/oauth_protocol) that says May 5 was the end of support for XOAUTH.  The next time this might come up seems to be [if/when XOAUTH2 goes away in favor of something more standardized](http://stackoverflow.com/a/24514691/131129).

[Here is a log comparison](https://dl.dropboxusercontent.com/u/7256610/xoauth-to-xoauth2.html) of the two attempts.

**Comment by jberkel** [comment]
I just checked the app, it actually does already support XOAuth2, however if you connect using the web flow it will still use XOAuth1. When authenticating using Android's AccountManager XOAuth2 is used. @opello maybe you still had an old token stored.

**Comment by opello** [comment]
@jberkel Very likely, I'm going on a few years with this phone and install.  @mtomana probably was in the same situation.  I only checked for issues after resolving it and wondering if it was reasonable to think I should have been prompted to upgrade tokens.  :)

**Comment by jberkel** [comment]
ok, so there will only be a problem for people who have an old token stored and for some reason can't use the android account manager. then there's also a big group of people who don't check the app (because it's running in the background) so it might make sense to release an update which automatically migrates old tokens.

**Comment by phireman481** [comment]
I'm completely illiterate when it comes to these things...that is why I donate to the developers. You guys do amazing work. Is there a timeframe for the update to fix the problem? I hate not having this backup to my Gmail.

**Comment by jberkel** [comment]
@phireman481 does the disconnect / reconnect trick @opello mentioned not work for you?

**Comment by phireman481** [comment]
I'm completely illiterate when it comes to these things...that is why I donate to the developers. You guys do amazing work. Is there a timeframe for the update to fix the problem? I hate not having this backup to my Gmail.

**Comment by phireman481** [comment]
@jberkel I honestly have no idea how to do that

**Comment by phireman481** [comment]
I honestly have no idea how to do that

**Comment by opello** [comment]
@phireman481 Open SMS Backup+, uncheck "Connect," then follow [these steps](https://github.com/jberkel/sms-backup-plus#user-content-faq-revoke-access) to revoke the auth token.  Once that's all done go back to SMS Backup+ and check "Connect" again, basically [follow these steps](https://github.com/jberkel/sms-backup-plus#user-content-first-steps).

The major down side to this approach is items that were added between the last successful sync and the first new sync will be lost.  At least that's my understanding -- because I believe if you back up everything again you will have duplicates.  But I might be wrong on this point.

**Comment by phireman481** [comment]
@opello Got it. Works perfectly again. Thanks so much for all the help.

**Comment by ealprr** [comment]
As mentioned, following @opello methods will force a full sync of all events.
That should not be a problem for call and sms/mms log in Gmail because Gmail automatically delete duplicate messages (at least, in my case, I did not have duplicate logs).
However for calendar call log, it will duplicate events.

Here is a solution I used to clean my calendar:
1. Connect [Google AppScript](https://script.google.com/) and create an empty project
2. Copy/paste the following:  
````javascript
// Set the calendar's name and the date range with duplicate event
var fromDate = new Date(2015,2,4,0,0,0); // March, 4 2015
var toDate = new Date(2015,4,7,0,0,0); // May, 7 2015
var calendarName = 'Call Log';

var delete_duplicate = false; // before deleting events, please check if parameters are correct

/**
 * Check 'calendarName's events between 'fromDate' and 'endDate' and report total number of events and number of duplicate events
 */
function processCalendar() {  
  var calendar = CalendarApp.getCalendarsByName(calendarName)[0];
  var events = calendar.getEvents(fromDate, toDate);
  
  var i = 0;
  var nb_duplicate = 0;
  
  while (i < events.length - 1) {
    var ev1 = events[i];
    var ev2 = events[i+1];
    
    // Log firsts and latest events to check 'calendarName', 'fromeDate' and 'toDate' parameters
    if (i < 6 || i > events.length-7) Logger.log('"'+ev1.getTitle()+'" ['+ev1.getStartTime()+' -> '+ev1.getEndTime()+']');
    
    // Check if the two events are equals (based on title, start and end time)
    if (ev1.getTitle() == ev2.getTitle() && 
      ev1.getStartTime().toString() == ev2.getStartTime().toString() && 
      ev1.getEndTime().toString() == ev2.getEndTime().toString())
    {
      nb_duplicate++;
      i += 2;
      
      if (!delete_duplicate) {continue;}
      // Delete the most recently added event
      if (ev1.getDateCreated() < ev2.getDateCreated()) ev2.deleteEvent();
      else ev1.deleteEvent();
    }
    else
      i++;
  }
  Logger.log("# total nb of event: " + events.length);
  Logger.log("# nb of duplicate event: " + nb_duplicate);
};
```
3. In the first lines customize ```fromDate```, ```toDate``` and ```calendarName```. **Ensure that ```delete_duplicate``` is set to false**.
4. Save and choose a name for the project (for instance: ```Google Calendar tool```).
5. Choose ```processCalendar``` function and run it ; allow Calendar access if asked.
6. Check output in ```View > Logs``` (ctrl+return) to validate parameters choosed in step 3.
7. If parameters are correct, set ```delete_duplicate``` to true and re-run ```processCalendar```.

**Comment by haridsv** [comment]
@ealprr are you sure that we will not end up with duplicates if we choose to backup sms and call log again? I had this broken for the last 3 days so I don't want to choose skip unless the other option causes duplicates. I am guessing that the dedupe (if at all it is working) would be done by SMS Backup + itself and not by gmail.

**Comment by ealprr** [comment]
I am sure that Gmail delete duplicate messages.
Otherwise you would end up with duplicate messages when you send an email to a mailing-list which you suscribed (or any other way of receiving the same message several times.)
There is also the way Gmail expose labels though smtp which is folder: to apply labels to an email you need to copy/move the message in the desired folders. Hopefully, you do not duplicate the message for each label.
Finally, I recently did a full sync with ```SMS Backup+``` with about 6k messages already synchronized and did not find duplicate.

However, you need to ensure to use the same ```mail address style``` in settings.

**Comment by haridsv** [comment]
Thanks @ealprr, appreciate your clarification.

**Comment by ctash** [comment]
Thanks @opello! Those steps worked, I did have to do a full backup, as noted by @ealprr, but since I just unchecked and rechecked "connect", all my settings should be the same (which hopefully means no duplicates).

**Comment by kflaming1** [comment]
I have SMS Backup+ running in the background so I had hundreds of messages that weren't backed up by the time I noticed "Server does not support XOAUTH".

Here's what I've done:
I turned on access for less secure apps in Google Mail.
I turned on plain text authorization in SMS Backup+.
I filled in my email address and password . 
I started a manual backup In SMS Backup+.
SMS Backup+ successfully logged in and backed up several hundred new messages including the call log.
I re-enabled XOAuth authorization in SMS Backup+.
I turned off access for less secure apps in Google Mail.
I disconnected and reconnected my Gmail account in SMS Backup+.
I skipped the initial backup because everything was now current.

I chose this approach to back up the items that were added between the last successful sync and the first new sync while avoiding the chance of any duplication. 

I'm just hoping the disconnect/reconnect cleared out any old auth tokens because I'm not exactly sure on the procedure for doing that if it doesn't happen automatically.

**Comment by jseideman** [comment]
hi there--

amazing app.  one of my favorites, and the one i send everyone to when they get a new phone.

now...this pesky XOAuth thing.  my phone is older (DROID X running android 2.3.4) and therefore i cannot use the android account manager (unless i can??).  I updated to 1.5.8 today (because of the android 2.x compatibility fixes) but i am still getting the XOAuth authorization error (and yes, IMAP is enabled in my gmail).  Will there be a release that will also migrate the auth tokens?  I would rather not have to disconnect from my account and lose my sync history if possible, and as I have an older phone, wont i still have to go through the web interface to authorize?

thanks!

**Comment by jberkel** [comment]
@jseideman yes it will happen, don't want to promise any exact dates though!

**Comment by jseideman** [comment]
That's great!  I know you said earlier in his thread that it may happen...I
was curious if it had made the leap from 'maybe' to 'yes it will happen'

Thanks!

**Comment by haridsv** [comment]
Right now, the only two options are to skip all or backup everything. With thousands of SMS on my phone, I dread having to backup all (even though it doesn't seem to cause any duplicates), so I am experimenting with adding a setting to specify a date from which to backup the messages. I noticed that in the code, it uses `-1` as the lower bound for the epoch timestamp initially, so I modified it to use a user specified preference. It seems to work nicely, except for a small issue with saving the preference (you may have to have to try multiple times to save the preference). Would anybody like to try it out and send me feedback? You can build it from my fork here:

https://github.com/haridsv/sms-backup-plus

For your convenience, I also created a binary release:

https://github.com/haridsv/sms-backup-plus/releases/tag/1.5.9-BETA4-HARI

I still have to figure out how to create resources for this preference, but it is hardcoded to show in English. The preference is at "Advanced Settings > Backup Settings > Backup Since Date".

**Comment by opello** [comment]
@haridsv I had considered this approach as well, wondering if I could use adb and sqlite3 (or something else) to manually reset the "last sync" date.  I didn't pursue it as far as you because I only looking at losing 2 phone calls.

What I actually ended up doing was deleting all of my SMS and MMS messages and allowing sms-backup-plus to restore them.  This took quite a while, but resulted in no lost data as far as I can tell.

Maybe some instructions for changing this wherever it persists would be a good manual solution for those facing this problem?

**Comment by haridsv** [comment]
@opello I am a little paranoid in that sense. I lost about 5 days of sms and call log as I chose to skip all, probably not a big deal, but I wanted to get my hands dirty and I had a bit of time too. If I can get some feedback, then I could try to create a PR.

**Comment by Smsbackup** [comment]
in 5/5/2015 my apps error by "Server does not support XOAUTH". for replace, i switching to plain text authentication but apps can't backup automatically, it just succeed in manual: fill all blank such as imap address,user nam/password anh click backup each time i login my apps. Who know why? help me, i want it auto.

**Comment by opello** [comment]
@Smsbackup If you have a current backup, try the steps [mentioned above](https://github.com/jberkel/sms-backup-plus/issues/554#issuecomment-100086950).

**Comment by Smsbackup** [comment]
disconnect / reconnect as opello mentioned not work for me. The URL of the consent screen includes the string /oauth1, google said "you must migrate to OAuth 2.0". So sad for me. Do Opello know some apps like sms backup+ who auto sent sms backup to mail as schedule.

**Comment by castanedaru** [comment]
Is not work for me too, from 01.06.2015 is trouble. "google no longer supports OAuth 1.0, you must migrate to OAuth 2.0 "
Your made amazing app. Please, fix it. i hope, that it possible.

**Comment by jberkel** [comment]
hello everybody, can you please try this release: https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA4

there's support for automatically migrating tokens in it but not sure if this works, since i cannot test it (impossible to get old xoauth1 tokens). it should automatically happen, but you might need to trigger the backup twice.

**Comment by jberkel** [comment]
try https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA5 instead

**Comment by jberkel** [comment]
Nobody able to test this? I'd like to do a new release soon
@castanedaru @Smsbackup

**Comment by castanedaru** [comment]
Thank you!
I use version 1.5.9 on Android 5.0.2. No any troubles more.

**Comment by jberkel** [comment]
great, thanks for the feedback. closing.

**Comment by drHeimskirk** [comment]
Sorry to add to a closed bug but just wanted to give you some more information.
The 1.5.9 update finally made it to Google play and I updated today.

I could still not do a backup.

The logcat shows the following...
06-27 19:31:19.552   757  1408 W SMSBackup+: invalid response from server: HTTP/1.1 400 Bad Request
06-27 19:31:19.552   757  1408 W SMSBackup+: did not get a refresh token

This is on Android 2.2.

Is there something else that I should try or should I attempt the steps mentioned above to get things back on track.

Thanks.
