### ISSUE TITLE
Manual backup button not working

### ISSUE THREAD

**Issue by Golden64** [jberkel/sms-backup-plus#577]
Hello,

Tried doing a manual backup today and received the normal backup confirmation message, but the backup never started.  Status continues to say idle and nothing happens.  My last backup was in April, so I'm really hoping there is a fix for this that doesn't require that I clear the local sync state.

Device info:
Samsung Galaxy S III SGH-I747
Android 4.4.2
SMS backup + version 1.5.9

Thanks for any help.

**Comment by dg4u** [comment]
It might be helpful for troubleshooting your problem to enable the sync log in debug mode (Advanced settings) and attach a relevant portion of it. The sync log is located on your SD card as "sms_backup_plus.log".

To attach the sync log create a "gist" (https://gist.github.com) and link to the gist you created instead of posting the full content in the issue.

**Comment by damitas** [comment]
Hi, I've just encountered an error with a manual backup.  When I click on the back-up button I get Error - Cannot connect.

Is that cannot connect due to network/wi-fi issues or cannot connect to my gmail?
here is the log
[Manual Backup Log] (https://gist.github.com/damitas/9f51b99e7073a467177e7ae058985aca)

**Comment by jcrben** [comment]
1.5.9 is prior to the current release.

Please try out the beta and open a new issue if it doesn't work https://github.com/jberkel/sms-backup-plus#beta
