### ISSUE TITLE
Lost messages on 1st back up

### ISSUE THREAD

**Issue by Stacie925** [jberkel/sms-backup-plus#641]
Hi lost some messages on 1st back up.
Droid razr

**Comment by atheompson** [comment]
If you send and receive messages on your Android everyday, then you should have encountered the same problem. Messaging help you easily communicate with others. But due to certain reasons like deletion, formatting, rooting, update crash, software failure, virus attack, etc some or all of your saved messages on Android can get lost/deleted. Don’t fret. You can get them back with great chances of success. What you need is a professional [Android messages recovery](http://www.android-rescuer.com/recover-deleted-messages-from-android-phone.html).

There is a mass of different data recovery tools available to recover photos and videos from Android SD card, but free recovery software supports SMS recovery from Android. Here I recommend you Android messages recovery, which can help you directly recover text messages from Android and also help you on [How to recover sms from Samsung galaxy/note](http://www.android-rescuer.com/recover-text-messages-from-samsung-galaxy.html). All popular Android brands are supported, such as, Samsung, HTC, LG, Sony, Motorola, and more. Just download its free trail version and give it a try.

**Comment by Woi** [comment]
I suggest to close this issue: Report does not contain any useful information, it has been used for spamming and it's nearly 2 years old.
