### ISSUE TITLE
Counts down to 0 items backed up

### ISSUE THREAD

**Issue by gnatbean** [jberkel/sms-backup-plus#703]
Auto backup seems not to be happening and when I hit manual backup it says "0/2300 items backed up" then the 2300, the total to be backed up, starts counting down until it says "0 items successfully backed up"
I tried uninstalling and reinstalling.

**Comment by tominkozhimala** [comment]
I'm having the same issue. Neither automatic or manual backups are working. No items have been backed up to my Gmail since October 27. 

# Device:
* Google Pixel 32gb
* Android 7.1.1
* SMS Backup+ 1.5.11 (beta tester)

# I have tried:
* Uninstall/Reinstall
* disconnect app from Google account and reauthorize

Log:
* [sms_backup_plus.log](https://gist.github.com/tominkozhimala/0b6daae96288d2af69d307db2da7b9b4)

**Comment by tominkozhimala** [comment]
@gnatbean I was able to resolve this on my own. 
Go to Advanced Settings > Backup Settings > Set "Only backup items from a specific group" to "Everybody" 

It seems this was set to "Starred" by default when I installed and re-installed the app to my device.
