### ISSUE TITLE
SMS/Call Log Policy Changes on Google Play

### ISSUE THREAD

**Issue by m-p-3** [jberkel/sms-backup-plus#934]
Will you apply for a permanent permission, or should we expect the app to be delisted from the Play Store at some point?

[Android Developers Blog: Reminder SMS/Call Log Policy Changes](https://android-developers.googleblog.com/2019/01/reminder-smscall-log-policy-changes.html)

**Comment by mikehardy** [comment]
Maybe a plug-in / minimal app on F-Droid that uses the permissions and implements a ContentProvider for call log / sms log.

Or maybe this app becomes f-droid only, but provides a ContentProvider for the same that helps the whole ecosystem of effected apps...

Just brainstorming. There are legitimate reasons to use the permissions that Google nevertheless does not want to permit. And I can understand their stance to a point, while still wanting the access, with proper disclosure and permission always of course.

**Comment by MysticMagican** [comment]
In my case, I'll use (and need) the app only for the call log feature in the last years. Simply because SMS is dead in my opinion. And for me it doesn't matter where I can find the app, play store, fdroid or just self hosted (on github e.g.). Important only : keep it alive and provide a way to donate - so maybe it isn't the baddest when removed  from the store as it avoids fees to Google I can imagine. :)

**Comment by jberkel** [comment]
I applied for an exception which got approved recently. 😌

**Comment by mikehardy** [comment]
That's actually pretty cool, I'd heard stories of rejections but had not heard of stories of approvals. Cheers

**Comment by jberkel** [comment]
However, there are some [other policy changes](https://developers.google.com/terms/api-services-user-data-policy#additional-requirements-for-specific-api-scopes) in place now which only allow certain types of apps access to Gmail. From what I can gather, storing non-email content on Gmail is no longer allowed.
