### ISSUE TITLE
What is the reason the app to ask for IMAP credentials;

### ISSUE THREAD

**Issue by lepidas** [jberkel/sms-backup-plus#955]
I don't understand what is the reason or the purpose for me to put my email server credentials. Why the app is asking for those login info;
If someone can explain, I hink it's something I don't understand but what is that...
thank you.

**Comment by zetaomegagon** [comment]
Since this app backs up your SMS and MMS messages to your email acct, you need to allow it access. Otherwise the developer would just wave their fingers and have access to any email account ever, or this app just wouldn't work.

If you use Gmail with 2 factor authentication, you will need to generate an App Specific Password and use that for the password field.

**Comment by lepidas** [comment]
The point is what is the reason to backup to gmail and not local. If it's local why it's asking for gmail login;

**Comment by zetaomegagon** [comment]
> The point is what is the reason to backup to gmail and not local.

Well, you can respond to SMS backed up to email in email. You don't have to worry about backing up local data (off phone). If you trust your IMAP server, then you don't have to worry about security/privacy...

I mean...that is a really subjective question and you'd really need to ask that to anyone who uses this app.

> If it's local why it's asking for gmail login

It's not local **at all**. Please read the app description.

If you want local backups only, I think SMS Gate can do that.

**Comment by kurahaupo** [comment]
@zetaomegagon thanks for adding the explanation
