### ISSUE TITLE
Any text message that was long gets cut off in the back up in Gmail

### ISSUE THREAD

**Issue by Jasmine1086** [jberkel/sms-backup-plus#996]
Any message that was longer and needs to be 'expanded' to view on my Samsung Galaxy S9 Plus is not fully backed up in Gmail - the message is not fully there so I have incomplete back-ups. 

* Android version; 9
* Phone model / brand; galaxy s9 plus
* SMS Backup+ version installed : 1.5.11
* Messaging app ; native SMS

**Comment by kurahaupo** [comment]
The first possibility is that SMS messages longer than 160 bytes are received as fragments, and something is blocking reassembly of those fragments when SMS Backup+ requests them.

@Jasmine1086 when you say "longer", how long exactly? Does it happen to all messages over a certain length (especially 160 bytes) or does it sometimes not happen to longer messages or does happen to shorter messages? Does it correlate with any other factors such as who sent the message?

The second option may be related to Advanced Messaging, if the sender is additionally sending AM when messages overflow a single (160 byte) SMS. However if the sender switched entirely to AM then the messages would not show at all, because SMS Backup+ does not (yet) handle AM and all such messages are ignored.

@Jasmine1086 please can you check whether you have a facility called "Advanced Messages" or "RCS" enabled on your phone? If this problem predominantly affects messages from a few people, can you ask them to check this as well, and report back?

**Comment by kurahaupo** [comment]
no response, closing issue
